version: '3.8'

services:
  bot:
    build: .
    container_name: telegram-forwarder-bot
    restart: always
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
